// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB47kBswrOaIioG1Ogswj_FSdNCAqfrOBM',
    appId: '1:109270563407:web:1a694520104492b2b5c83a',
    messagingSenderId: '109270563407',
    projectId: 'task-login-2f35e',
    authDomain: 'task-login-2f35e.firebaseapp.com',
    storageBucket: 'task-login-2f35e.appspot.com',
    measurementId: 'G-0TBPVWFS4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwgVXSIIVbfoUcCP2JiKfbGd87h8KEieA',
    appId: '1:109270563407:android:dd69ad28a7ac5055b5c83a',
    messagingSenderId: '109270563407',
    projectId: 'task-login-2f35e',
    storageBucket: 'task-login-2f35e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAexwA4MqFQWqN5VtVjc2dIHMaMTxSU08s',
    appId: '1:109270563407:ios:e7f7bd4bb04e67b7b5c83a',
    messagingSenderId: '109270563407',
    projectId: 'task-login-2f35e',
    storageBucket: 'task-login-2f35e.appspot.com',
    iosBundleId: 'com.example.taskLoginScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAexwA4MqFQWqN5VtVjc2dIHMaMTxSU08s',
    appId: '1:109270563407:ios:e7f7bd4bb04e67b7b5c83a',
    messagingSenderId: '109270563407',
    projectId: 'task-login-2f35e',
    storageBucket: 'task-login-2f35e.appspot.com',
    iosBundleId: 'com.example.taskLoginScreen',
  );
}
